name: reactcicd

on:
    push:
        branches: [test]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy NodeJS app
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: '100.27.81.159'
                  username: 'ubuntu'
                  key: ${{ secrets.SSHKEY2 }}
                  script: sudo sh /var/www/frontend_sem.sh
