name: reactcicd

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy NodeJS app
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: '44.218.99.120'
                  username: 'ubuntu'
                  key: ${{ secrets.SSHKEY }}
                  script: sudo sh /var/www/frontend_sem.sh
